#include "mex.h"
#include "./visual_studios/inpainting_algorithm/shared_library/shared_library.h"
 
/* 
%Release compile command
OCVRoot = 'C:\Users\Andrew Powell\Documents\opencv\build';
IPath_0 = ['-I',fullfile(OCVRoot,'include')];
IPath_1 = ['-I','.\visual_studios\inpainting_algorithm\shared_library'];
LPath_0 = fullfile(OCVRoot,'x64\vc11\staticlib');
LPath_1 = ['.\visual_studios\inpainting_algorithm\x64\Release'];
libs = {...
    'kernel32.lib',...
    'user32.lib',...
    'gdi32.lib',...
    'winspool.lib',...
    'shell32.lib',...
    'ole32.lib',...
    'oleaut32.lib',...
    'uuid.lib',...
    'comdlg32.lib',...
    'advapi32.lib',...
    'comctl32.lib',...
    'setupapi.lib',...
    'ws2_32.lib',...
    'vfw32.lib',...
	fullfile(LPath_1,'shared_library.lib'),...
    fullfile(LPath_0,'IlmImf.lib'),...
    fullfile(LPath_0,'libjasper.lib'),...
    fullfile(LPath_0,'libjpeg.lib'),... 
    fullfile(LPath_0,'libpng.lib'),... 
    fullfile(LPath_0,'libtiff.lib'),... 
    fullfile(LPath_0,'opencv_calib3d2410.lib'),... 
    fullfile(LPath_0,'opencv_contrib2410.lib'),... 
    fullfile(LPath_0,'opencv_core2410.lib'),... 
    fullfile(LPath_0,'opencv_features2d2410.lib'),... 
    fullfile(LPath_0,'opencv_flann2410.lib'),... 
    fullfile(LPath_0,'opencv_gpu2410.lib'),... 
    fullfile(LPath_0,'opencv_highgui2410.lib'),... 
    fullfile(LPath_0,'opencv_imgproc2410.lib'),... 
    fullfile(LPath_0,'opencv_legacy2410.lib'),... 
    fullfile(LPath_0,'opencv_ml2410.lib'),...
    fullfile(LPath_0,'opencv_nonfree2410.lib'),... 
    fullfile(LPath_0,'opencv_objdetect2410.lib'),... 
    fullfile(LPath_0,'opencv_ocl2410.lib'),...
    fullfile(LPath_0,'opencv_photo2410.lib'),... 
    fullfile(LPath_0,'opencv_stitching2410.lib'),... 
    fullfile(LPath_0,'opencv_superres2410.lib'),... 
    fullfile(LPath_0,'opencv_ts2410.lib'),...
    fullfile(LPath_0,'opencv_video2410.lib'),... 
    fullfile(LPath_0,'opencv_videostab2410.lib'),... 
    fullfile(LPath_0,'zlib.lib')}; 
mex('perform_bertalmio_pde_inpainting_mex_0.cpp',IPath_0,IPath_1,libs{:},'LINKFLAGS="/NODEFAULTLIB:msvcrt.lib"');
 */

void mexFunction(int nlhs, mxArray *plhs[],
                 int nrhs, const mxArray *prhs[]) {
    
    /* Declarations */
    int m = mxGetM(prhs[0]); // nrows
    int n = mxGetN(prhs[0]); // ncols
    plhs[0] = mxCreateNumericMatrix(m,n,mxSINGLE_CLASS,mxREAL);  
    float* input_array = (float*)mxGetData(prhs[0]);
    float* mask_array = (float*)mxGetData(prhs[1]);
    float* output_array = (float*)mxGetData(plhs[0]);
    int* total_iters = (int*)mxGetData(prhs[2]);
    int* total_inpaint_iters = (int*)mxGetData(prhs[3]);
    int* total_anidiffuse_iters = (int*)mxGetData(prhs[4]);
    int total_stages = mxGetScalar(prhs[5]);
    float* delta_ts = (float*)mxGetData(prhs[6]);
    float* sensitivities = (float*)mxGetData(prhs[7]);
    int diffuse_coef = mxGetScalar(prhs[8]);
    
    /* Run algorithm */
    perform_bertalmio_pde_inpainting_0(
        input_array,mask_array,output_array, 
        m,n,
        total_iters,total_inpaint_iters,total_anidiffuse_iters,total_stages,
        delta_ts,sensitivities,diffuse_coef);
}