function output_array = perform_bertalmio_pde_inpainting_3(...
    input_array,mask_array,...
    total_iters,total_inpaint_iters,total_anidiffuse_iters,total_stages,...
    delta_ts,sensitivities,diffuse_coef)

output_array = perform_bertalmio_pde_inpainting_mex_0(...
    single(input_array),single(mask_array),...
    int32(total_iters),int32(total_inpaint_iters),int32(total_anidiffuse_iters),int32(total_stages),...
    single(delta_ts),single(sensitivities),int32(diffuse_coef));

end