/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_native_project_MainActivity */

#ifndef _Included_com_example_native_project_MainActivity
#define _Included_com_example_native_project_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_native_project_MainActivity
 * Method:    native_setup
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_example_native_1project_MainActivity_native_1setup
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_example_native_project_MainActivity
 * Method:    native_reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_native_1project_MainActivity_native_1reset
  (JNIEnv *, jobject);

/*
 * Class:     com_example_native_project_MainActivity
 * Method:    native_destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_native_1project_MainActivity_native_1destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_example_native_project_MainActivity
 * Method:    native_get_pixels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_native_1project_MainActivity_native_1get_1pixels
  (JNIEnv *, jobject);

/*
 * Class:     com_example_native_project_MainActivity
 * Method:    native_perform
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_native_1project_MainActivity_native_1perform
  (JNIEnv *, jobject);

/*
 * Class:     com_example_native_project_MainActivity
 * Method:    native_update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_native_1project_MainActivity_native_1update
  (JNIEnv *, jobject);

/*
 * Class:     com_example_native_project_MainActivity
 * Method:    perform_proposed_inpainting_0
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_example_native_1project_MainActivity_perform_1proposed_1inpainting_10
  (JNIEnv *, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
